// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "adder": Application User Types
//
// Command:
// $ goagen
// --design=github.com/obieq/rva-devops-2017/design
// --out=$(GOPATH)/src/github.com/obieq/rva-devops-2017
// --version=v1.2.0-dirty

package app
